-- MySQL Script generated by MySQL Workbench
-- śro, 16 maj 2018, 17:46:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 16_kulaga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 16_kulaga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `16_kulaga` DEFAULT CHARACTER SET utf8 ;
USE `16_kulaga` ;

-- -----------------------------------------------------
-- Table `16_kulaga`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`user_role` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`calendar` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`calendar` (
  `token` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`user` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `user_role_id` INT NOT NULL,
  `calendar_id` INT NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id`, `calendar_id`),
  INDEX `fk_user_user_role_idx` (`user_role_id` ASC),
  INDEX `fk_user_calendar1_idx` (`calendar_id` ASC),
  CONSTRAINT `fk_user_user_role`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `16_kulaga`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_calendar1`
    FOREIGN KEY (`calendar_id`)
    REFERENCES `16_kulaga`.`calendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `16_kulaga`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`media` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`media` (
  `id` INT NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `img` VARCHAR(128) NOT NULL,
  `width` INT NOT NULL,
  `height` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`event` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `content` MEDIUMTEXT NULL,
  `start` DATE NOT NULL,
  `end` DATE NOT NULL,
  `cost` INT NULL,
  `token` VARCHAR(45) NOT NULL,
  `seats` INT NULL,
  `calendar_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  INDEX `fk_event_calendar1_idx` (`calendar_id` ASC),
  CONSTRAINT `fk_event_calendar1`
    FOREIGN KEY (`calendar_id`)
    REFERENCES `16_kulaga`.`calendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`participant` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`participant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_participant_event1_idx` (`event_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_participant_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `16_kulaga`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`tags` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `media_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`media_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`media_tags` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`media_tags` (
  `media_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_media_tags_media1_idx` (`media_id` ASC),
  INDEX `fk_media_tags_tags1_idx` (`tags_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_media_tags_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `16_kulaga`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `16_kulaga`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`event_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`event_tags` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`event_tags` (
  `tags_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_event_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_event_tags_event1_idx` (`event_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `16_kulaga`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_tags_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `16_kulaga`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`user_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`user_media` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`user_media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `media_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_media_media1_idx` (`media_id` ASC),
  INDEX `fk_user_media_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_media_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `16_kulaga`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_media_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `16_kulaga`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `16_kulaga`.`user_role`
-- -----------------------------------------------------
START TRANSACTION;
USE `16_kulaga`;
INSERT INTO `16_kulaga`.`user_role` (`id`, `user_role`) VALUES (1, 'MAIN_ADMIN');
INSERT INTO `16_kulaga`.`user_role` (`id`, `user_role`) VALUES (2, 'CALENDAR_ADMIN');
INSERT INTO `16_kulaga`.`user_role` (`id`, `user_role`) VALUES (3, 'CALENDAR_USER');

COMMIT;

