-- MySQL Script generated by MySQL Workbench
-- pią, 22 cze 2018, 15:53:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 16_kulaga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 16_kulaga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `16_kulaga` DEFAULT CHARACTER SET utf8 ;
USE `16_kulaga` ;

-- -----------------------------------------------------
-- Table `16_kulaga`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`role` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`user` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`user` (
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `role_id` INT NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `16_kulaga`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `16_kulaga`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`calendar` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`calendar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`media` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `photo` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`event` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `content` VARCHAR(700) NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NULL,
  `cost` INT NULL,
  `seats` INT NULL,
  `calendar_id` INT NOT NULL,
  `sign_up` TINYINT(1) NULL,
  `main_img` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_calendar1_idx` (`calendar_id` ASC),
  CONSTRAINT `fk_event_calendar1`
    FOREIGN KEY (`calendar_id`)
    REFERENCES `16_kulaga`.`calendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`participant` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`participant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_participant_event1_idx` (`event_id` ASC),
  CONSTRAINT `fk_participant_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `16_kulaga`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`tags` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`media_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`media_tags` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`media_tags` (
  `media_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_media_tags_media1_idx` (`media_id` ASC),
  INDEX `fk_media_tags_tags1_idx` (`tags_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_media_tags_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `16_kulaga`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `16_kulaga`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`event_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`event_tags` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`event_tags` (
  `tags_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_event_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_event_tags_event1_idx` (`event_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `16_kulaga`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_tags_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `16_kulaga`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`user_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`user_media` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`user_media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `media_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_media_media1_idx` (`media_id` ASC),
  INDEX `fk_user_media_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_media_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `16_kulaga`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_media_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `16_kulaga`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`user_calendars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`user_calendars` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`user_calendars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `calendar_id` INT NOT NULL,
  `user_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `calendar_id`),
  INDEX `fk_user_calendar_user1_idx` (`user_id` ASC),
  INDEX `fk_user_calendar_calendar1_idx` (`calendar_id` ASC),
  CONSTRAINT `fk_user_calendar_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `16_kulaga`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_calendar_calendar1`
    FOREIGN KEY (`calendar_id`)
    REFERENCES `16_kulaga`.`calendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `16_kulaga`.`calendar_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `16_kulaga`.`calendar_media` ;

CREATE TABLE IF NOT EXISTS `16_kulaga`.`calendar_media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `media_id` INT NOT NULL,
  `calendar_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calendar_media_media1_idx` (`media_id` ASC),
  INDEX `fk_calendar_media_calendar1_idx` (`calendar_id` ASC),
  CONSTRAINT `fk_calendar_media_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `16_kulaga`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_media_calendar1`
    FOREIGN KEY (`calendar_id`)
    REFERENCES `16_kulaga`.`calendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
