-- MySQL Script generated by MySQL Workbench
-- pią, 11 maj 2018, 12:14:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 16_kulaga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 16_kulaga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `16_kulaga` DEFAULT CHARACTER SET utf8 ;
USE `16_kulaga` ;

-- -----------------------------------------------------
-- Table `16_kulaga`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`users` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `user_role` INT(3) NOT NULL DEFAULT 0,
  `current_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC));


-- -----------------------------------------------------
-- Table `16_kulaga`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`tags` (
  `id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `16_kulaga`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`media` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `img` VARCHAR(255) NULL,
  `width` INT NULL,
  `height` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`calendars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`calendars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`events` (
  `Id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(255) NULL,
  `start` DATE NULL,
  `end` DATE NULL,
  `cost` INT NULL,
  `url` VARCHAR(60) NULL,
  `seats` INT NULL,
  `calendars_id` INT NOT NULL,
  PRIMARY KEY (`Id`, `calendars_id`),
  INDEX `fk_events_calendars1_idx` (`calendars_id` ASC),
  CONSTRAINT `fk_events_calendars1`
    FOREIGN KEY (`calendars_id`)
    REFERENCES `16_kulaga`.`calendars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`participants` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`events_has_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`events_has_participants` (
  `events_Id` INT NOT NULL,
  `participants_id` INT NOT NULL,
  PRIMARY KEY (`events_Id`, `participants_id`),
  INDEX `fk_events_has_participants_participants1_idx` (`participants_id` ASC),
  INDEX `fk_events_has_participants_events1_idx` (`events_Id` ASC),
  CONSTRAINT `fk_events_has_participants_events1`
    FOREIGN KEY (`events_Id`)
    REFERENCES `16_kulaga`.`events` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_participants_participants1`
    FOREIGN KEY (`participants_id`)
    REFERENCES `16_kulaga`.`participants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`events_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`events_has_tags` (
  `events_Id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`events_Id`, `tags_id`),
  INDEX `fk_events_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_events_has_tags_events1_idx` (`events_Id` ASC),
  CONSTRAINT `fk_events_has_tags_events1`
    FOREIGN KEY (`events_Id`)
    REFERENCES `16_kulaga`.`events` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `16_kulaga`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`users_has_calendars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`users_has_calendars` (
  `users_id` INT NOT NULL,
  `calendars_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `calendars_id`),
  INDEX `fk_users_has_calendars_calendars1_idx` (`calendars_id` ASC),
  INDEX `fk_users_has_calendars_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_calendars_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `16_kulaga`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_calendars_calendars1`
    FOREIGN KEY (`calendars_id`)
    REFERENCES `16_kulaga`.`calendars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `16_kulaga`.`media_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`media_has_tags` (
  `media_id` INT NOT NULL,
  `media_user_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`media_id`, `media_user_id`, `tags_id`),
  INDEX `fk_media_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_media_has_tags_media1_idx` (`media_id` ASC, `media_user_id` ASC),
  CONSTRAINT `fk_media_has_tags_media1`
    FOREIGN KEY (`media_id` , `media_user_id`)
    REFERENCES `16_kulaga`.`media` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `16_kulaga`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`events_has_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`events_has_media` (
  `events_Id` INT NOT NULL,
  `events_calendars_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  `media_user_id` INT NOT NULL,
  PRIMARY KEY (`events_Id`, `events_calendars_id`, `media_id`, `media_user_id`),
  INDEX `fk_events_has_media_media1_idx` (`media_id` ASC, `media_user_id` ASC),
  INDEX `fk_events_has_media_events1_idx` (`events_Id` ASC, `events_calendars_id` ASC),
  CONSTRAINT `fk_events_has_media_events1`
    FOREIGN KEY (`events_Id` , `events_calendars_id`)
    REFERENCES `16_kulaga`.`events` (`Id` , `calendars_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_media_media1`
    FOREIGN KEY (`media_id` , `media_user_id`)
    REFERENCES `16_kulaga`.`media` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `16_kulaga`.`users_has_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `16_kulaga`.`users_has_media` (
  `users_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  `media_user_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `media_id`, `media_user_id`),
  INDEX `fk_users_has_media_media1_idx` (`media_id` ASC, `media_user_id` ASC),
  INDEX `fk_users_has_media_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_media_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `16_kulaga`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_media_media1`
    FOREIGN KEY (`media_id` , `media_user_id`)
    REFERENCES `16_kulaga`.`media` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
