-- MySQL Script generated by MySQL Workbench
-- śro, 9 maj 2018, 01:48:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema skelet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema skelet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skelet` DEFAULT CHARACTER SET utf8 ;
USE `skelet` ;

-- -----------------------------------------------------
-- Table `skelet`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skelet`.`users` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `admin_privileges` TINYINT(1) NOT NULL DEFAULT 0,
  `current_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `skelet`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skelet`.`tags` (
  `id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `skelet`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skelet`.`media` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `img` VARCHAR(255) NULL,
  `width` INT NULL,
  `height` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_madia_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_madia_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `skelet`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skelet`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skelet`.`events` (
  `Id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(255) NULL,
  `start` DATE NULL,
  `end` DATE NULL,
  `cost` INT NULL,
  `url` VARCHAR(60) NULL,
  `seats` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skelet`.`participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skelet`.`participants` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skelet`.`events_has_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skelet`.`events_has_participants` (
  `events_Id` INT NOT NULL,
  `participants_id` INT NOT NULL,
  PRIMARY KEY (`events_Id`, `participants_id`),
  INDEX `fk_events_has_participants_participants1_idx` (`participants_id` ASC),
  INDEX `fk_events_has_participants_events1_idx` (`events_Id` ASC),
  CONSTRAINT `fk_events_has_participants_events1`
    FOREIGN KEY (`events_Id`)
    REFERENCES `skelet`.`events` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_participants_participants1`
    FOREIGN KEY (`participants_id`)
    REFERENCES `skelet`.`participants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skelet`.`events_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skelet`.`events_has_tags` (
  `events_Id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`events_Id`, `tags_id`),
  INDEX `fk_events_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_events_has_tags_events1_idx` (`events_Id` ASC),
  CONSTRAINT `fk_events_has_tags_events1`
    FOREIGN KEY (`events_Id`)
    REFERENCES `skelet`.`events` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `skelet`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skelet`.`tags_has_madia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skelet`.`tags_has_madia` (
  `tags_id` INT NOT NULL,
  `madia_id` INT NOT NULL,
  PRIMARY KEY (`tags_id`, `madia_id`),
  INDEX `fk_tags_has_madia_madia1_idx` (`madia_id` ASC),
  INDEX `fk_tags_has_madia_tags1_idx` (`tags_id` ASC),
  CONSTRAINT `fk_tags_has_madia_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `skelet`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_has_madia_madia1`
    FOREIGN KEY (`madia_id`)
    REFERENCES `skelet`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
